/*
 * Flight API
 * API for managing flights
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.auth;

import io.swagger.client.Pair;

import lombok.Getter;
import lombok.Setter;
import okhttp3.Credentials;
import java.util.Map;
import java.util.List;


@Getter
@Setter
public class HttpBasicAuth implements Authentication {
    private String username;
    private String password;

    @Override
    public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams) {
        if (username == null && password == null) {
            return;
        }
        headerParams.put("Authorization", Credentials.basic(
            username == null ? "" : username,
            password == null ? "" : password));
    }
}
