/*
 * Flight API
 * API for managing flights
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client;

import lombok.Getter;
import lombok.Setter;

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:17:55.833273080Z[GMT]")
public class Configuration {
    /**
     * -- GETTER --
     *  Get the default API client, which would be used when creating API
     *  instances without providing an API client.
     * <p>
     *
     * -- SETTER --
     *  Set the default API client, which would be used when creating API
     *  instances without providing an API client.
     *
     */
    @Setter
    @Getter
    private static ApiClient defaultApiClient = new ApiClient();

}
